import React from "react"
import { Accordion } from "./Accordion"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Accordion,
  "https://www.figma.com/design/BqFF0vvbUxGaAE0KbaHSKR?node-id=7753%3A4779",
  {
    props: {},
    example: (props) => <Accordion />,
  },
)
