import React from "react"
import { Tab } from "./Tab"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Tab,
  "https://www.figma.com/design/BqFF0vvbUxGaAE0KbaHSKR?node-id=3729%3A12963",
  {
    props: {
      label: figma.string("Label"),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
      }),
      active: figma.boolean("Active"),
    },
    example: (props) => <Tab />,
  },
)
