import React from "react"
import { Avatar } from "./Avatar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  "https://www.figma.com/design/BqFF0vvbUxGaAE0KbaHSKR?node-id=9762%3A1103",
  {
    props: {
      initials: figma.string("Initials"),
      type: figma.enum("Type", {
        Initial: "initial",
        Image: "image",
      }),
      size: figma.enum("Size", {
        Large: "large",
        Small: "small",
        Medium: "medium",
      }),
      shape: figma.enum("Shape", {
        Circle: "circle",
        Square: "square",
      }),
    },
    example: (props) => <Avatar />,
  },
)
